version: '3.1'
services:
  frontend:
    build: frontend
    ports:
      - 9090:9090
  backend:
    build: backend
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
